config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # after_sign_in to: 'mains#test'
  # landing page
  
  devise_for :users
  
  root to: 'mains#home'
  get '/errors' => 'mains#error'

  resources :locations, only: [:show, :index] do 
    
    resources :dailies, only: [:new, :create, :edit, :update, :destroy] do 
      member { get 'status' }
    end

    resources :monthlies, only: [:new, :create, :edit, :update, :destroy]

  end


  # devise_scope :user do 
  # 	get 'users/sign_in', to: 'mains#test'
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily.rb
class Daily < ApplicationRecord
	# Associations
	belongs_to :user
	belongs_to :location

	# Validations
	validates :color, :make, :ticket_no, :price, :user_id, :location_id, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
	has_many :dailies
	has_many :monthlies

	validates :name, presence: true, uniqueness: true
end

app/models/monthly.rb
class Monthly < ApplicationRecord
	# Associations
	belongs_to :user
	belongs_to :location

	# Validations
	validates :first, :last, :phone, :make, :color, :price, :user_id, :location_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  # validations
  validates :username, presence: true, uniqueness: true
  validates :username, length: { minimum: 2, too_short: "has to be more then %{count} characters."}

  # Associations
  has_many :dailies
  has_many :monthlies
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    attributes = [:username, :email]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
	
	include ApplicationHelper

	before_action :secure
	before_action :setup_location, only: [:new, :create, :destroy, :update, :edit]
	before_action :setup_daily, only: [:edit, :update, :destroy, :status]

	def new
		@daily = Daily.new
	end

	def create
		@daily = Daily.new(daily_params)
		@daily.location_id = @location.id
		@daily.user_id = current_user.id
		if @daily.save
			redirect_to location_path(@location), flash: { notice: 'Car has been added successfully !' }
		else
			@errors = @daily.errors.full_messages
			render :new
		end
	end

	def edit
	end

	def update
		if @daily.update(daily_params) 
		redirect_to location_path @location, flash: { notice: 'Car has been updated successfully .' } 
		else
		render :edit
		end
	end

	def destroy
		@daily.destroy
		redirect_to location_path	@location, notice: 'Car has been removed !'
	end

	def status
		@location = Location.find(params[:location_id])
		@daily.paid ? @daily.update(paid: false) : @daily.update(paid: true)
		redirect_to location_path(@location)
	end

	private

	def setup_location
		@location = Location.find(params[:location_id])	
	end

	def setup_daily
		@daily = Daily.find(params[:id])
	end

	def daily_params
		params.require(:daily).permit(:color, :make, :ticket_no, :price, :paid)
	end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	
	include ApplicationHelper	

	before_action :secure
	$sort = nil
	
	def index
		@locations = Location.all
	end

	def show
		@location = Location.find(params[:id])
		@monthlies = Monthly.where(location_id: @location.id)
		
		if params[:sort] then $sort = params[:sort] end
		
		$sort ? @dailies = Daily.where(location_id: @location.id).order($sort).order(created_at: :desc) : @dailies = Daily.where(location_id: @location.id).order(created_at: :desc)
		@paid, @unpaid = @dailies.partition(&:paid)
		@total = @paid.map(&:price).reduce(:+)
	end

end










# <h2> <%= ((Time.now - (@location.dailies[0].created_at))/60) %> </h2>

# <h3> <%= DateTime.now %> </h3>

# <h3>  <%= Date.yesterday %> </h3>

# <h3> <%= (1.day.ago) - Time.now %></h3>

app/controllers/mains_controller.rb
class MainsController < ApplicationController

	def home
		!current_user ? redirect_to(new_user_session_path) : @locations = Location.all
	end

	def test
	end
	
end

app/controllers/monthlies_controller.rb
class MonthliesController < ApplicationController

	include ApplicationHelper

	before_action :setup_location, only: [:new, :create, :destroy, :update, :edit]
	before_action :setup_monthly, only: [:edit, :update, :destroy]

	def new
		@monthly = Monthly.new
	end

	def create
		@monthly = Monthly.new(monthly_params)
		@monthly.location_id = @location.id
		@monthly.user_id = current_user.id
		if @monthly.save
			redirect_to location_path(@location), flash: { notice: 'Monthly client has been added successfully .' }
		else
			@errors = @monthly.errors.full_messages
			render :new
		end
	end

	def edit
	end

	def update
		if @monthly.update(monthly_params)
			redirect_to location_path @location
		else
		render :edit
		end
	end

	def destroy
		@monthly.destroy
		redirect_to location_path @location
	end

	private

	def setup_monthly
		@monthly = Monthly.find(params[:id])
	end

	def setup_location
		@location = Location.find(params[:location_id])	
	end	

	def monthly_params
		params.require(:monthly).permit(:first, :last, :phone, :make, :color, :ticket_no, :price, :paid )
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def secure
		if !current_user then redirect_to :root end
	end

end

app/views/dailies/_form_daily.html.erb
<%= form_for [@location, @daily], class: 'form-inline' do |f| %>
		
		<div class="row">
	    <div class="field form-group col-md-3">
				<%= f.label 'Ticket #' %>
				<small class="text-muted"> enter the ticket number </small>
				<%= f.text_field :ticket_no, class: 'form-control' %>
			</div>
		</div>
		
		<div class="row">
			<div class="field form-group col-md-4">
				<%= f.label 'Make' %>
				<small class="text-muted"> Min 3 characters</small> <span id="red"> * </span>
				<%= f.text_field :make, autofocus: true, class: 'form-control mx-sm-3' %>
			</div>
			
	    <div class="field form-group col-md-4">
				<%= f.label 'color' %>
				<small class="text-muted"> Min 3 characters</small> <span id="red"> * </span>
				<%= f.text_field :color, class: 'form-control' %>
			</div>
		</div>

		<div class="row">			
	    <div class="field form-group col-md-2 col-xs-5">
				<%= f.label 'price' %> <span id="red"> * </span>
				<div class="input-group mb-2 mb-sm-0">
					<div class="input-group-addon">$</div>
					<%= f.number_field :price, class: 'form-control' %>
				</div>
			</div>

			<fieldset disabled>
						<div class="field form-group col-md-6 col-xs-8">
							<%= f.label 'user ?' %>
							<%= f.text_field :user_id, placeholder: current_user.username, class: 'form-control' %>
					</div>
			</fieldset>
		</div>

		<div class="field form-check">
			<%= f.label 'paid', class: 'form-check-label' %>
			<%= f.check_box :paid, class: 'form-check-input' %>
		</div>

		<br>

		<p> <small id="red"> * fields required ! </small> </p>

		<br>
			<%= f.submit class: 'btn btn-lg btn-block btn-success' %>
		<br>

	<% end %>

app/views/dailies/edit.html.erb
<div class="container">
	
	<h2> Edit Daily Form</h2>

	<%= render 'form_daily' %>

	<%= link_to '<- Back ', :back, class: 'btn btn-sm btn-primary' %>

</div>

app/views/dailies/new.html.erb
<div class="container">
	
	<h3>New Daily Car for <em id="red"> <%= @location.name %> </em> </h3>

	<br>

	<% if @errors %>
			<% @errors.each do |e| %> <p id="red"> <%= e %> </p> <% end %> 
	<% end %>

	<%= render 'form_daily' %>

	<%= link_to '<- Back ', :back, class: 'btn btn-sm btn-primary' %>

</div>

app/views/layouts/_alert_modal.html.erb
<!-- Logout Modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header"> 
      	<h4> Are you sure you want to log out ? </h4>
      </div>
      <div class="modal-footer">
      	<%= link_to 'Cancel', '', data: { dismiss: 'modal' }, class: 'btn btn-danger' %>
        <%= link_to 'Yes', destroy_user_session_path, method: :delete, class: 'btn btn-success' %>`
      </div>
    </div>
  </div>
</div>

app/views/layouts/_devise.html.erb
<!-- #devise -->
<% if notice || alert %>
  <p class="notice" id="green"><%= notice %></p>
  <p class="alert" id="red"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container-fluid text-center">
    <a href="#myPage" title="To Top">
      <span class="glyphicon glyphicon-chevron-up"></span>
    </a>
    <p>Back to Top</p>
</footer>

app/views/layouts/_navbar.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top bg-faded"> 
      <div class="container-fluid">
        <div class="navbar-header"> 
          <%= link_to 'GSP', :root, class: 'navbar-brand' %>
      <% if current_user %>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"> </span>
          <span class="icon-bar"> </span>
          <span class="icon-bar"> </span>
        </button>
      <% end %>
        </div>

        
          <% if current_user %>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav navbar-right">
            <!-- <li><a href="#about">ABOUT</a></li> -->
            <li> <em class="navbar-brand" id="green"> <%= current_user.username %> </em> </li>
            <li> <em class="navbar-brand"> <%= link_to 'Edit me', edit_user_registration_path, class: 'btn btn-sm btn-warning' %> </em> </li>
            <li> <em class="navbar-brand"> <%= link_to 'Log out', '#logoutModal' , data: { toggle: 'modal' }, class: 'btn btn-sm btn-danger' %> </em> </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_navbar_bottom.html.erb
<nav class="navbar navbar-fixed-bottom bg-faded"> 
	<div class="container">
  	<p> <%= link_to '<- Back', :back, class: 'btn btn-primary btn-sm' %> 
  	<%= link_to 'Add a new daily', new_location_daily_path(@location), class: 'btn btn-warning btn-lg' %> </p>
	</div>
</nav>

app/views/layouts/_navbar_bottom_monthly.html.erb
<nav class="navbar navbar-fixed-bottom bg-faded"> 
	<div class="container">
		<p>
  		<%= link_to '<- Back', :back, class: 'btn btn-primary btn-sm' %>
  		<%= link_to 'Add a new monthly client', new_location_monthly_path(@location), class: 'btn btn-warning btn-lg' %> </p>
	</div>
</nav>

app/views/layouts/_script.html.erb
<script>

 // For Footer

  $(document).ready(function(){
    // Add smooth scrolling to all links in navbar + footer link
    $(".navbar a, footer a[href='#myPage']").on('click', function(event) {
      // Make sure this.hash has a value before overriding default behavior
      if (this.hash !== "") {
        // Prevent default anchor click behavior
        event.preventDefault();

        // Store hash
        var hash = this.hash;

        // Using jQuery's animate() method to add smooth page scroll
        // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
        $('html, body').animate({
          scrollTop: $(hash).offset().top
        }, 1500, function(){
     
          // Add hash (#) to URL when done scrolling (default click behavior)
          window.location.hash = hash;
        });
      } // End if
    });
  })

 
  // For login button scroll down on mainpage

  $(document).ready(function() {
    $("div a[href='#login']").on('click', function(event) {
      if (this.hash !== "") {
        event.preventDefault();

        var hash = this.hash;

        $('html, body').animate({
          scrollTop: $(hash).offset().top
        }, 1500, function(){
          window.location.hash = hash;
        })
      }
    })
  })
  

  // Google MAps fo 17th street

  function myMap() {
  var myCenter = new google.maps.LatLng(37.763404, -122.422360);
  var mapProp = {center:myCenter, zoom:16, scrollwheel:false, draggable:false, mapTypeId:google.maps.MapTypeId.ROADMAP};
  var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
  var marker = new google.maps.Marker({position:myCenter});
  marker.setMap(map);
  }


  
  // table filter

  $(document).ready(function(){
    $("#mySearch").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });


</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS"] %>&callback=myMap"></script>



<!-- 
  For test
 -->

<script>
  
  $(document).ready(function(){
    $('#show-link').on('click', function(e) {
      e.preventDefault
      $('#testdiv').hide()
      // alert('Clicked !')
    })
  })

  $(document).ready(function() {
    $('#paid').click(function(event) {
      // event.preventDefault()
      // alert('MMMM')
    })
  })

</script>



<!--  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>G.S.Parking</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <!-- <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> -->
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="padding-top: 50px" id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60" >
  


  <% if flash[:notice] %>
    <div style="text-align: center;" class="container alert alert-success alert-dismissible" role='alert' >
      <strong> <%= flash[:notice] %> </strong> 
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div style="text-align: center;" class="container alert alert-danger alert-dismissible" role='alert'>
      <strong> <%= flash[:alert] %> </strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>


    
    <%= render 'layouts/navbar' %>

    <%= render 'layouts/alert_modal' %>
    
    <%= yield %>

  </body>
</html>

app/views/locations/_search_field.html.erb
<div class="input-group">
  	<input class="form-control col-md-2" id="mySearch" type="text" placeholder="Search.." autofocus="true">
  	<div class="input-group-btn">
      <button class="btn btn-default" type="submit">
        <i class="glyphicon glyphicon-search"></i>
      </button>
    </div>
</div>

app/views/locations/_table.html.erb
<style type="text/css">
  th,td { text-align: center; }
</style>

<table class="table table-hover table-bordered table-responsive">
    <thead class="thead-dark">
      <tr class="info">
        <th style="width: 1px"> NO </th>
        <th style="width: 2px"> <%= link_to 'Ticket Number', sort: 'ticket_no' %> </th>
        <th style="width: 5px"> <%= link_to 'Color', sort: 'color' %> </th>
        <th style="width: 5px"> <%= link_to 'Make', sort: 'make' %> </th>
        <th style="width: 5px"> <%= link_to 'Price', sort: 'price' %> </th>
        <th style="width: 5px"> <%= link_to 'Paid ?', sort: 'paid' %></th>
        <th style="width: 5px"> <%= link_to 'Added by User', sort: 'user_id' %> </th>
        <th style="width: 2px"> Edit / Delete </th>
      </tr>
    </thead>

    <% @dailies.each.with_index(1) do |d,i| %>
      <tbody id="dailyTable">
      <% if d.paid %> <tr class="success"> <% else %> <tr class="danger"> <% end %>
        
        <td> <%= i %> </td>

        <td> <%= d.ticket_no %> </td>
        <td> <%= d.color %> </td>
        <td> <%= d.make %> </td>
        <td> $ <%= d.price %> </td>
        
        <% if d.paid %>
          <td> <%= link_to '- Paid -', status_location_daily_path(@location, d), class: "btn btn-sm btn-success" %> </td>
        <% else %>
          <td> <%= link_to 'Unpaid', status_location_daily_path(@location, d), class: "btn btn-sm btn-danger" %> </td>
        <% end %>

        <td> <%= User.find(d.user_id).username %> </td>
        <td> 
        <% if d.user_id == current_user.id %>
          <%= link_to 'E', edit_location_daily_path(@location, d), class: 'btn btn-xs btn-info' %>
          <%= link_to 'D', location_daily_path(@location, d), method: :delete, data: { confirm: "Are you sure to delete ? \n \n#{d.color} #{d.make} with a ticket number #{d.ticket_no} ?" }, class: 'btn btn-xs btn-danger' %> 
        <% else %>
          <i id="red"> N / A </i>   
        <% end %>
        </td>

      </tr>
    <% end %>
    </tbody>

  </table>

app/views/locations/_table_daily.html.erb
<style type="text/css">
  th,td { text-align: center; }
</style>

<table class="table table-hover table-responsive table-condensed">
    <thead class="thead-dark">
      <tr class="info">
        <th style="width: 1px"> NO </th>
        <th style="width: 2px"> <%= link_to 'Ticket Number', sort: 'ticket_no' %> </th>
        <th style="width: 5px"> <%= link_to 'Color', sort: 'color' %> </th>
        <th style="width: 5px"> <%= link_to 'Make', sort: 'make' %> </th>
        <th style="width: 5px"> <%= link_to 'Price', sort: 'price' %> </th>
        <th style="width: 5px"> <%= link_to 'Paid ?', sort: 'paid' %></th>
        <th style="width: 5px"> <%= link_to 'Added by User', sort: 'user_id' %> </th>
        <th style="width: 2px"> Edit / Delete </th>
      </tr>
    </thead>

    <% @dailies.each.with_index(1) do |d,i| %>
      <tbody id="table">
      <% if d.paid %> <tr class="success"> <% else %> <tr class="danger"> <% end %>
        
        <td> <%= i %> </td>

        <td> <%= d.ticket_no %> </td>
        <td> <%= d.color %> </td>
        <td> <%= d.make %> </td>
        <td> $ <%= d.price %> </td>
        
        <% if d.paid %>
          <td> <%= link_to '- Paid -', status_location_daily_path(@location, d), class: "btn btn-sm btn-success", id: 'paid' %> </td>
        <% else %>
          <td> <%= link_to 'Unpaid', status_location_daily_path(@location, d), class: "btn btn-sm btn-danger", id: 'unpaid' %> </td>
        <% end %>

        <td> <%= User.find(d.user_id).username %> </td>
        <td> 
        <% if d.user_id == current_user.id %>
          <%= link_to 'E', edit_location_daily_path(@location, d), class: 'btn btn-xs btn-info' %>
          <%= link_to 'D', location_daily_path(@location, d), method: :delete, data: { confirm: "Are you sure to delete ? \n \n#{d.color} #{d.make} with a ticket number #{d.ticket_no} ?" }, class: 'btn btn-xs btn-danger' %> 
        <% else %>
          <i id="red"> N / A </i>   
        <% end %>
        </td>

      </tr>
    <% end %>
    </tbody>

  </table>

app/views/locations/_table_monthly.html.erb
<style type="text/css">
  th,td { text-align: center; }
</style>

<table class="table table-hover table-responsive table-condensed table-striped">
	
	<thead class="thead-dark">
		<tr class="info">
			<th> No </th>
			<th> Firstname </th>
			<th> Lastname </th>
			<th> Phone # </th>
			<th> Car Make </th>
			<th> Car Color </th>
			<th> Price </th>
			<th> Paid by ? </th>
			<th> Added by ? </th>
		</tr>
	</thead>

	<tbody id="table">
		<% @monthlies.each.with_index(1) do |m,i| %>
		<tr>
			<td> <%= i %> </td>
			<td> <%= m.first %> </td>
			<td> <%= m.last %> </td>
			<td> <%= m.phone %> </td>
			<td> <%= m.make %> </td>
			<td> <%= m.color %> </td>
			<td> <%= m.price %> </td>
			<td> <%= m.paid %> </td>
			<td> <%= User.find(m.user_id).username %> </td>
		</tr>
		<% end %>
	</tbody>

</table>

app/views/locations/index.html.erb
<% @locations.each do |l| %>
	<li> <%= l.name %> </li>
<% end %>

app/views/locations/show.html.erb
<div class="container">
  
  <h3> <em id="red"> <%= @location.name %> </em> </h3>
  
  
  <%= render 'search_field' %>

  <br>

  <ul class="nav nav-pills nav-tabs">
  	<li class="active"> <%= link_to 'Dailies', '#home', data: { toggle: 'pill' } %> </li>
    <li> <%= link_to 'Monthlies', '#menu1', data: { toggle: 'pill' } %> </li>
    <% if current_user.username == 'meric' %>
    <li> <%= link_to 'Location', '#menu2', data: { toggle: 'pill' } %> </li>
    <% end %>
  </ul>


  <div class="tab-content">
    
    <div id="home" class="tab-pane fade in active">
    	<br>
  		<%= render 'table_daily' %>
		  
		  <div class="row textcenter">
		  	
		  	<div class="col-md-3">
			  	<h3 id="red"> Unpaid = <%= @unpaid.count %> car(s) </h3>
		  	</div>
		  
				<div class="col-md-3">
			  	<h3 id="green"> Paid = <%= @paid.count %> car(s) </h3>
		  	</div>
		  
		  	<div class="col-md-3">
					<h3 id="blue"> Daily Total = $ <%= @total ? @total : '0' %> </h3>
			  </div>
			
				<%= render 'layouts/navbar_bottom' %>
			</div>
			
    </div>
    
    <div id="menu1" class="tab-pane fade">
    	<br>
      <%= render 'table_monthly' %>
			
			<%= render 'layouts/navbar_bottom_monthly' %>
		</div>

			
		<% if current_user.username == 'meric' %>
		<div id="menu2" class="tab-pane fade" >
				
			<%= link_to 'show div', '#', class: 'btn btn-primary btn-lg', id: 'show-link' %>

			<div id="testdiv">
				
		 		<h2 id="red" class="textcenter">
		 		
		 			TEST DIVISION

		 		</h2>
			
			</div>


		</div>
		<% end %>

	</div>

	<br>
	<br>
	<%= render 'layouts/footer' %>
	
	<%= render 'layouts/script' %>

	<br>
	<br>
	<br>


</div>

app/views/mains/error.html.erb
<h4 id="red"> You have NO ACCESS to this page !</h4>

<h3 id="green"> <%= link_to 'Click here to go to HomePage ...', :root %> </h3>

app/views/mains/home.html.erb
<div class="container">
	
		<h2 style="text-align: center" > Welcome , <span id="red"> <%= current_user.username %> </span> ! </h2>
		
		<br>

		<p> Choose a <em id="red"> location </em> please .. </p>
		
		<br>

		<% @locations.each.with_index(1) do |l,i| %>
	  	<p> <%= link_to "#{l.name}", location_path(l.id), class: "btn btn-primary btn-lg btn-block" %> </p>
			<br>
		<% end %>

	<br>

</div>


<!--  -->

app/views/mains/test.html.erb
<h1> TEST PAGE !!! </h1>

app/views/monthlies/_form_monthly.html.erb
<%= form_for [@location, @monthly], class: 'form-inline' do |f| %>

	<div class="row">
		<div class="field form-group col-md-3 col-xs-4">
			<%= f.label 'Firstname' %>
			<%= f.text_field :first, class: 'form-control', autofocus: true %>
		</div>

		<div class="field form-group col-md-3 col-xs-4">
			<%= f.label 'Lastname' %>
			<%= f.text_field :last, class: 'form-control' %>
		</div>

		<div class="field form-group col-md-3 col-xs-4">
			<%= f.label 'Phone Number' %>
			<%= f.text_field :phone, class: 'form-control' %>
		</div>
	</div>

	<br>

	<div class="row">
		<div class="field form-group col-md-3 col-xs-8">
			<%= f.label 'Ticket Number' %> 
			<%= f.text_field :ticket_no, class: 'form-control' %> 
			<small class="text-muted"> Enter the monthly pass number </small>
		</div>

		<div class="field form-group col-md-3 col-xs-6">
			<%= f.label 'Car Make/Model' %>
			<%= f.text_field :make, class: 'form-control' %>
		</div>

		<div class="field form-group col-md-3 col-xs-6">
			<%= f.label 'Car Color' %>
			<%= f.text_field :color, class: 'form-control' %>
		</div>
	</div>

	<br>

	<div class="row">
		<div class="field form-group col-md-2 col-xs-4">
			<%= f.label 'Price' %>
			<%= f.number_field :price, class: 'form-control' %>
		</div>

		<div class="field form-group col-md-2 col-xs-6">
			<%= f.label 'Paid ?' %>
			<small class="text-muted" id="red"> Cash or Check ? </small>
			<%= f.select :paid, ['by Cash', 'by Check'], class: 'form-control', include_blank: true %>
		</div>
	</div>

	<p> <small id="red"> All fields are required ! </small> </p>

	<br>
	<%= f.submit class: 'btn btn-lg btn-success btn-block' %>
	<br>

<% end %>

app/views/monthlies/edit.html.erb
<div class="container">
	
	<h2> Edit Monthly Form</h2>

	<%= render 'form_monthly' %>

	<%= link_to '<- Back ', :back, class: 'btn btn-sm btn-primary' %>

</div>

app/views/monthlies/new.html.erb
<div class="container">
	
	<h3>New Monthly Car for <em id="red"> <%= @location.name %> </em> </h3>

	<br>

	<% if @errors %>
			<% @errors.each do |e| %> <p id="red"> <%= e %> </p> <% end %> 
	<% end %>

	<%= render 'form_monthly' %>

	<%= link_to '<- Back ', :back, class: 'btn btn-sm btn-primary' %>

</div>